name: phoenix-connectors preCommit Build

on: 
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: mvn -B clean install -DskipTests
    # The build doesn't seem to pick up the result of the install from above, so just re-compile
    # and the Maven reactor will find it just fine.
    - name: Test
      run: mvn -B verify
